# Generated by Django 5.2.3 on 2025-07-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('anios_experiencia', models.IntegerField(default=0)),
                ('especialidad_culinaria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_cocina', models.CharField(max_length=100)),
                ('capacidad_meses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_plato', models.FloatField()),
                ('ingredientes_principales', models.CharField(max_length=200)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='negocio.chef')),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='negocio.restaurante'),
        ),
    ]
